/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BodyStyleGuidesUpdateStyleGuide {
    /** The name of the style guide. */
    name?: string;
    /** List of domain IDs to filter terminology searches by. NULL or empty list means no filtering. */
    terminology_domain_ids?: string[];
}
