/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface BodyStyleGuidesUpdateStyleGuide {
    /** The name of the style guide. */
    name: string;
}
