/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface StyleGuideRequestBody {
    /** A friendly name for your style guide to help you identify it later. If left empty, we'll generate one for you. */
    name?: string;
}
