/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface StyleGuideRequestBody {
    /** A friendly name for your style guide to help you identify it later. */
    name: string;
}
