/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file_upload: fs.createReadStream("/path/to/your/file"),
 *         name: "name"
 *     }
 */
export interface StyleGuideRequestBody {
    /** The document to analyze. We accept PDF files (.pdf) up to 2 MB. */
    file_upload: core.file.Uploadable.FileLike;
    /** A friendly name for your style guide to help you identify it later. */
    name: string;
}
