/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         delete_existing: true
 *     }
 */
export interface BodyTerminologyImportTerminology {
    /** Delete all existing terms, term sets and domains before importing */
    delete_existing?: boolean;
    /** CSV or ACTIF XML file containing terminology data */
    file: core.file.Uploadable.FileLike;
}
