/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../../../../index.js";

/**
 * @example
 *     {
 *         term: "term",
 *         type: "preferred"
 *     }
 */
export interface TermUpdateRequest {
    term: string;
    type: MarkupAI.TermType;
}
