/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: 1,
 *         page_size: 1,
 *         search: "search"
 *     }
 */
export interface TerminologyListDomainsRequest {
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    page_size?: number;
    /** Optional name filter */
    search?: string;
}
