/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: 1,
 *         page_size: 1,
 *         search_term: "search_term"
 *     }
 */
export interface TerminologyListTermSetsRequest {
    /** Page number (1-based) */
    page?: number;
    /** Number of items per page */
    page_size?: number;
    /** Optional search term to filter term sets */
    search_term?: string;
    /** Optional domain filter (any of these domains) */
    domain_ids?: string | string[];
}
