/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface TermSetUpdateRequest {
    instructions?: string;
    domain_ids?: string[];
}
