/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface TerminologySearchTerminologyRequest {
    query: string;
    /** Optional domain filter */
    domain_ids?: string | string[];
}
