/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../../../../index.js";

/**
 * @example
 *     {
 *         instructions: "instructions"
 *     }
 */
export interface TermSetCreateRequest {
    instructions: string;
    terms?: MarkupAI.TermCreateRequest[];
    domain_ids?: string[];
}
