/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as MarkupAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";
import * as fs from "fs";

export declare namespace Terminology {
    export interface Options {
        environment?: core.Supplier<environments.MarkupAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Manage term sets and terms.
 */
export class Terminology {
    protected readonly _options: Terminology.Options;

    constructor(_options: Terminology.Options) {
        this._options = _options;
    }

    /**
     * Exports all term sets, terms and domains to CSV. The exported CSV follows the same format as the CSV import.
     *
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.exportTerminology()
     */
    public exportTerminology(requestOptions?: Terminology.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__exportTerminology(requestOptions));
    }

    private async __exportTerminology(
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling GET /v1/terminology.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Uploads a CSV or ACTIF XML file and imports terminology.
     *
     * **CSV Format Requirements:**
     * - CSV must include columns: Prohibited, Preferred, Context-Dependent, Instructions, Domains
     * - The first row must contain the column headers in the exact same order as shown above
     * - Multiple values within a single cell should be separated by semicolons with a space (e.g., term1; term2; term3)
     * - Empty cells are allowed
     * - The CSV import format is the same as the CSV export format.
     *
     * @param {MarkupAI.BodyTerminologyImportTerminology} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.terminology.importTerminology({
     *         file: fs.createReadStream("/path/to/your/file"),
     *         delete_existing: true
     *     })
     */
    public importTerminology(
        request: MarkupAI.BodyTerminologyImportTerminology,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.ImportSummary> {
        return core.HttpResponsePromise.fromPromise(this.__importTerminology(request, requestOptions));
    }

    private async __importTerminology(
        request: MarkupAI.BodyTerminologyImportTerminology,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.ImportSummary>> {
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (request.delete_existing != null) {
            _queryParams["delete_existing"] = request.delete_existing.toString();
        }

        const _request = await core.newFormData();
        await _request.appendFile("file", request.file);
        const _maybeEncodedRequest = await _request.getRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                ..._maybeEncodedRequest.headers,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.ImportSummary, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling POST /v1/terminology.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Searches the text for relevant terminology and returns matched term sets.
     *
     * Term sets are matched if any word sequence (up to 5 words) in the text is similar to one of the terms of the term set.
     * The similarity measure used is a trigram similarity of 0.5 or higher between the word sequence and the term.
     *
     * @param {MarkupAI.TerminologySearchTerminologyRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.searchTerminology({
     *         query: "query"
     *     })
     */
    public searchTerminology(
        request: MarkupAI.TerminologySearchTerminologyRequest,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TerminologySearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchTerminology(request, requestOptions));
    }

    private async __searchTerminology(
        request: MarkupAI.TerminologySearchTerminologyRequest,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TerminologySearchResponse>> {
        const { query, domain_ids: domainIds } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["query"] = query;
        if (domainIds != null) {
            if (Array.isArray(domainIds)) {
                _queryParams["domain_ids"] = domainIds.map((item) => item);
            } else {
                _queryParams["domain_ids"] = domainIds;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology/search",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TerminologySearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling GET /v1/terminology/search.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a pageable list of term sets with all their associated terms and domains.
     *
     * The search filter searches the term set instructions and term text fields.
     *
     * @param {MarkupAI.TerminologyListTermSetsRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.listTermSets({
     *         page: 1,
     *         page_size: 1,
     *         search_term: "search_term"
     *     })
     */
    public listTermSets(
        request: MarkupAI.TerminologyListTermSetsRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.PaginatedTermSetsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listTermSets(request, requestOptions));
    }

    private async __listTermSets(
        request: MarkupAI.TerminologyListTermSetsRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.PaginatedTermSetsResponse>> {
        const { page, page_size: pageSize, search_term: searchTerm, domain_ids: domainIds } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (searchTerm != null) {
            _queryParams["search_term"] = searchTerm;
        }

        if (domainIds != null) {
            if (Array.isArray(domainIds)) {
                _queryParams["domain_ids"] = domainIds.map((item) => item);
            } else {
                _queryParams["domain_ids"] = domainIds;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology/term-sets",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.PaginatedTermSetsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling GET /v1/terminology/term-sets.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new term set. Terms and domains are linked to term sets.
     * The term set instructions text will be used to determine whether a term should be flagged in the text and what the term replacement should be.
     *
     * @param {MarkupAI.TermSetCreateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.createTermSet({
     *         instructions: "instructions"
     *     })
     */
    public createTermSet(
        request: MarkupAI.TermSetCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermSetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTermSet(request, requestOptions));
    }

    private async __createTermSet(
        request: MarkupAI.TermSetCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermSetResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology/term-sets",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermSetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling POST /v1/terminology/term-sets.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.getTermSet("term_set_id")
     */
    public getTermSet(
        termSetId: string,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermSetWithTerms> {
        return core.HttpResponsePromise.fromPromise(this.__getTermSet(termSetId, requestOptions));
    }

    private async __getTermSet(
        termSetId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermSetWithTerms>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermSetWithTerms, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling GET /v1/terminology/term-sets/{term_set_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.deleteTermSet("term_set_id")
     */
    public deleteTermSet(
        termSetId: string,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteTermSet(termSetId, requestOptions));
    }

    private async __deleteTermSet(
        termSetId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling DELETE /v1/terminology/term-sets/{term_set_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {MarkupAI.TermSetUpdateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.updateTermSet("term_set_id")
     */
    public updateTermSet(
        termSetId: string,
        request: MarkupAI.TermSetUpdateRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermSetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateTermSet(termSetId, request, requestOptions));
    }

    private async __updateTermSet(
        termSetId: string,
        request: MarkupAI.TermSetUpdateRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermSetResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermSetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling PATCH /v1/terminology/term-sets/{term_set_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create terms that should be matched in the text. The term types are:
     *
     * * **preferred**: this is the preferred term for the associated term set
     * * **prohibited**: this term should not be used to talk about the term set
     * * **context_dependent**: this term is correct in certain cases, but incorrect in others, the instructions field of the term set should explain when the term is correct and when it is incorrect
     *
     * @param {string} termSetId - UUID of the term set
     * @param {MarkupAI.TermCreateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.createTerm("term_set_id", {
     *         term: "term",
     *         type: "preferred"
     *     })
     */
    public createTerm(
        termSetId: string,
        request: MarkupAI.TermCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTerm(termSetId, request, requestOptions));
    }

    private async __createTerm(
        termSetId: string,
        request: MarkupAI.TermCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}/terms`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling POST /v1/terminology/term-sets/{term_set_id}/terms.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {string} termId - UUID of the term
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.getTerm("term_set_id", "term_id")
     */
    public getTerm(
        termSetId: string,
        termId: string,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTerm(termSetId, termId, requestOptions));
    }

    private async __getTerm(
        termSetId: string,
        termId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}/terms/${encodeURIComponent(termId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling GET /v1/terminology/term-sets/{term_set_id}/terms/{term_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {string} termId - UUID of the term
     * @param {MarkupAI.TermUpdateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.updateTerm("term_set_id", "term_id", {
     *         term: "term",
     *         type: "preferred"
     *     })
     */
    public updateTerm(
        termSetId: string,
        termId: string,
        request: MarkupAI.TermUpdateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.TermResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateTerm(termSetId, termId, request, requestOptions));
    }

    private async __updateTerm(
        termSetId: string,
        termId: string,
        request: MarkupAI.TermUpdateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.TermResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}/terms/${encodeURIComponent(termId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.TermResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling PUT /v1/terminology/term-sets/{term_set_id}/terms/{term_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} termSetId - UUID of the term set
     * @param {string} termId - UUID of the term
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.deleteTerm("term_set_id", "term_id")
     */
    public deleteTerm(
        termSetId: string,
        termId: string,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteTerm(termSetId, termId, requestOptions));
    }

    private async __deleteTerm(
        termSetId: string,
        termId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/term-sets/${encodeURIComponent(termSetId)}/terms/${encodeURIComponent(termId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling DELETE /v1/terminology/term-sets/{term_set_id}/terms/{term_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {MarkupAI.TerminologyListDomainsRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.listDomains({
     *         page: 1,
     *         page_size: 1,
     *         search: "search"
     *     })
     */
    public listDomains(
        request: MarkupAI.TerminologyListDomainsRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.PaginatedDomainsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDomains(request, requestOptions));
    }

    private async __listDomains(
        request: MarkupAI.TerminologyListDomainsRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.PaginatedDomainsResponse>> {
        const { page, page_size: pageSize, search } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (pageSize != null) {
            _queryParams["page_size"] = pageSize.toString();
        }

        if (search != null) {
            _queryParams["search"] = search;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology/domains",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.PaginatedDomainsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling GET /v1/terminology/domains.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {MarkupAI.DomainCreateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.createDomain({
     *         name: "name"
     *     })
     */
    public createDomain(
        request: MarkupAI.DomainCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.DomainResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createDomain(request, requestOptions));
    }

    private async __createDomain(
        request: MarkupAI.DomainCreateRequest,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.DomainResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                "v1/terminology/domains",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.DomainResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError("Timeout exceeded when calling POST /v1/terminology/domains.");
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domainId - UUID of the domain
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.getDomain("domain_id")
     */
    public getDomain(
        domainId: string,
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.DomainResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDomain(domainId, requestOptions));
    }

    private async __getDomain(
        domainId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.DomainResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/domains/${encodeURIComponent(domainId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.DomainResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling GET /v1/terminology/domains/{domain_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domainId - UUID of the domain
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.deleteDomain("domain_id")
     */
    public deleteDomain(domainId: string, requestOptions?: Terminology.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDomain(domainId, requestOptions));
    }

    private async __deleteDomain(
        domainId: string,
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/domains/${encodeURIComponent(domainId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling DELETE /v1/terminology/domains/{domain_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domainId - UUID of the domain
     * @param {MarkupAI.DomainUpdateRequest} request
     * @param {Terminology.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MarkupAI.UnauthorizedError}
     * @throws {@link MarkupAI.ForbiddenError}
     * @throws {@link MarkupAI.UnprocessableEntityError}
     * @throws {@link MarkupAI.InternalServerError}
     *
     * @example
     *     await client.terminology.updateDomain("domain_id")
     */
    public updateDomain(
        domainId: string,
        request: MarkupAI.DomainUpdateRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): core.HttpResponsePromise<MarkupAI.DomainResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateDomain(domainId, request, requestOptions));
    }

    private async __updateDomain(
        domainId: string,
        request: MarkupAI.DomainUpdateRequest = {},
        requestOptions?: Terminology.RequestOptions,
    ): Promise<core.WithRawResponse<MarkupAI.DomainResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MarkupAIEnvironment.Default,
                `v1/terminology/domains/${encodeURIComponent(domainId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as MarkupAI.DomainResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MarkupAI.UnauthorizedError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MarkupAI.ForbiddenError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new MarkupAI.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MarkupAI.InternalServerError(
                        _response.error.body as MarkupAI.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MarkupAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MarkupAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MarkupAITimeoutError(
                    "Timeout exceeded when calling PATCH /v1/terminology/domains/{domain_id}.",
                );
            case "unknown":
                throw new errors.MarkupAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
