/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface AnalysisScore {
    clarity?: MarkupAI.ClarityScore;
    tone?: MarkupAI.ToneScore;
}
