/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BaseStyleGuideType = "ap" | "chicago" | "microsoft";
export const BaseStyleGuideType = {
    Ap: "ap",
    Chicago: "chicago",
    Microsoft: "microsoft",
} as const;
