/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface CheckOptions {
    style_guide?: MarkupAI.StyleGuide;
    dialect?: MarkupAI.Dialects;
    tone?: MarkupAI.Tones;
}
