/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClarityScore {
    average_sentence_length?: number;
    flesch_kincaid_grade?: number;
    flesch_reading_ease?: number;
    lexical_diversity?: number;
    score?: number;
    sentence_complexity?: number;
    sentence_count?: number;
    vocabulary_complexity?: number;
    word_count?: number;
}
