/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClarityCategory =
    | "Simpler Words"
    | "Complex Verb Tenses"
    | "Hidden Verbs"
    | "Direct Statements"
    | "Passive Voice"
    | "Phrasal Verbs"
    | "Formal Grammar Forms"
    | "Unnecessary Words"
    | "Sentence Splitting"
    | "Concise Wording";
export const ClarityCategory = {
    SimplerWords: "Simpler Words",
    ComplexVerbTenses: "Complex Verb Tenses",
    HiddenVerbs: "Hidden Verbs",
    DirectStatements: "Direct Statements",
    PassiveVoice: "Passive Voice",
    PhrasalVerbs: "Phrasal Verbs",
    FormalGrammarForms: "Formal Grammar Forms",
    UnnecessaryWords: "Unnecessary Words",
    SentenceSplitting: "Sentence Splitting",
    ConciseWording: "Concise Wording",
} as const;
