/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface ConfigOptions {
    dialect?: MarkupAI.Dialects;
    style_guide?: MarkupAI.StyleGuide;
    tone?: MarkupAI.Tones;
}
