/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConsistencyCategory =
    | "Consistent Punctuation"
    | "Consistent Capitalization"
    | "Numbers, Dates, and Times"
    | "Inclusive Language"
    | "Special Style Guide Requirements"
    | "other";
export const ConsistencyCategory = {
    ConsistentPunctuation: "Consistent Punctuation",
    ConsistentCapitalization: "Consistent Capitalization",
    NumbersDatesAndTimes: "Numbers, Dates, and Times",
    InclusiveLanguage: "Inclusive Language",
    SpecialStyleGuideRequirements: "Special Style Guide Requirements",
    Other: "other",
} as const;
