/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Dialects = "american_english" | "british_oxford" | "canadian_english";
export const Dialects = {
    AmericanEnglish: "american_english",
    BritishOxford: "british_oxford",
    CanadianEnglish: "canadian_english",
} as const;
