/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Dialects = "american_english" | "british_english" | "canadian_english";
export const Dialects = {
    AmericanEnglish: "american_english",
    BritishEnglish: "british_english",
    CanadianEnglish: "canadian_english",
} as const;
