/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DomainResponse {
    id: string;
    name: string;
    description?: string;
    created_at: string;
    updated_at: string;
    created_by?: string;
    updated_by?: string;
    term_set_count?: number;
}
