/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorResponse {
    /** A description of the error that occurred. */
    detail: string;
    /** the HTTP status code generated by the server for this issue */
    status: number;
    /** A unique ID associated with the HTTP request. */
    request_id: string;
}
