/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GrammarCategory =
    | "Grammar Agreement"
    | "Punctuation"
    | "Capitalization"
    | "Spelling"
    | "Sentence Structure"
    | "Verb Forms"
    | "Context Fit"
    | "other";
export const GrammarCategory = {
    GrammarAgreement: "Grammar Agreement",
    Punctuation: "Punctuation",
    Capitalization: "Capitalization",
    Spelling: "Spelling",
    SentenceStructure: "Sentence Structure",
    VerbForms: "Verb Forms",
    ContextFit: "Context Fit",
    Other: "other",
} as const;
