/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GrammarCategory = "sva_pronoun" | "punct_cap" | "spelling" | "syntax" | "verbs" | "word_usage" | "other";
export const GrammarCategory = {
    SvaPronoun: "sva_pronoun",
    PunctCap: "punct_cap",
    Spelling: "spelling",
    Syntax: "syntax",
    Verbs: "verbs",
    WordUsage: "word_usage",
    Other: "other",
} as const;
