/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ImportSummary {
    entries_processed?: number;
    term_sets_created?: number;
    term_sets_deleted?: number;
    terms_created_or_updated?: number;
    domains_created?: number;
    domains_deleted?: number;
    errors?: string[];
}
