/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface Issue {
    /** The original text */
    original: string;
    /** Position details of the issue */
    position: MarkupAI.Position;
    /** The sub-category of the change */
    subcategory: Issue.Subcategory;
    category?: MarkupAI.IssueCategory;
}

export namespace Issue {
    /**
     * The sub-category of the change
     */
    export type Subcategory =
        | MarkupAI.GrammarCategory
        | MarkupAI.ClarityCategory
        | MarkupAI.ToneCategory
        | MarkupAI.ConsistencyCategory
        | MarkupAI.TermReplaceCategory;
}
