/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IssueCategory =
    | "grammar"
    | "sentence_length"
    | "sentence_structure"
    | "simple_vocab"
    | "style_guide"
    | "terminology"
    | "tone";
export const IssueCategory = {
    Grammar: "grammar",
    SentenceLength: "sentence_length",
    SentenceStructure: "sentence_structure",
    SimpleVocab: "simple_vocab",
    StyleGuide: "style_guide",
    Terminology: "terminology",
    Tone: "tone",
} as const;
