/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IssueCategory = "clarity" | "grammar" | "consistency" | "terminology" | "tone";
export const IssueCategory = {
    Clarity: "clarity",
    Grammar: "grammar",
    Consistency: "consistency",
    Terminology: "terminology",
    Tone: "tone",
} as const;
