/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface PaginatedDomainsResponse {
    domains: MarkupAI.DomainResponse[];
    total_count: number;
    page: number;
    page_size: number;
    total_pages: number;
}
