/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

/**
 * Pageable response for term sets in term management UI
 */
export interface PaginatedTermSetsResponse {
    term_sets: MarkupAI.TermSetWithTerms[];
    total_count: number;
    total_unfiltered_term_sets: number;
    page: number;
    page_size: number;
    total_pages: number;
}
