/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface QualityScore {
    score?: number;
    grammar?: MarkupAI.GrammarScore;
    style_guide?: MarkupAI.StyleGuideScore;
    terminology?: MarkupAI.TerminologyScore;
}
