/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface RewriteResponse {
    workflow_id?: string;
    status?: MarkupAI.WorkflowStatus;
    scores?: MarkupAI.ScoreOutput;
    issues?: MarkupAI.Suggestion[];
    check_options?: MarkupAI.CheckOptions;
    /** The status code received and URL used when sending the webhook if a webhook URL was included when starting the process. */
    webhook_response?: MarkupAI.WebhookResponse;
    rewrite?: string;
    rewrite_scores?: MarkupAI.ScoreOutput;
}
