/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface ScoreOutput {
    quality?: MarkupAI.QualityScore;
    clarity?: MarkupAI.ClarityScore;
    grammar?: MarkupAI.GrammarScore;
    style_guide?: MarkupAI.StyleGuideScore;
    tone?: MarkupAI.ToneScore;
    terminology?: MarkupAI.TerminologyScore;
}
