/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface ScoreOutput {
    quality?: MarkupAI.QualityScore;
    analysis?: MarkupAI.AnalysisScore;
}
