/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SentenceLengthCategory =
    | "capitalization"
    | "remove"
    | "extract"
    | "shorten"
    | "deletion"
    | "replace"
    | "other";
export const SentenceLengthCategory = {
    Capitalization: "capitalization",
    Remove: "remove",
    Extract: "extract",
    Shorten: "shorten",
    Deletion: "deletion",
    Replace: "replace",
    Other: "other",
} as const;
