/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SentenceStructureCategory =
    | "complex_verbs"
    | "hidden_verbs"
    | "insertion"
    | "modal_verbs"
    | "passive"
    | "phrasal_verbs"
    | "subjunctive"
    | "other";
export const SentenceStructureCategory = {
    ComplexVerbs: "complex_verbs",
    HiddenVerbs: "hidden_verbs",
    Insertion: "insertion",
    ModalVerbs: "modal_verbs",
    Passive: "passive",
    PhrasalVerbs: "phrasal_verbs",
    Subjunctive: "subjunctive",
    Other: "other",
} as const;
