/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SimpleVocabCategory = "vocabulary" | "other";
export const SimpleVocabCategory = {
    Vocabulary: "vocabulary",
    Other: "other",
} as const;
