/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface StyleGuide {
    /** The type of style guide to use */
    style_guide_type?: MarkupAI.StyleGuides;
    /** The ID of the style guide to use */
    style_guide_id?: string;
}
