/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface StyleGuideResponse {
    id: string;
    /** The name of the style guide. */
    name: string;
    /** The UTC date and time the style guide was created. */
    created_at: string;
    /** The ID of the user who created the style guide. */
    created_by: string;
    /** The status of the submitted style guide. */
    status: MarkupAI.StyleGuideStatus;
    /** The UTC datetime that the style guide was last updated. If null, the style guide has never been updated. */
    updated_at?: string;
    /** The ID of the user who last updated the style guide. If null, the style guide has never been updated. */
    updated_by?: string;
}
