/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StyleGuideCategory =
    | "punctuation"
    | "capitalization"
    | "spelling_and_grammar"
    | "numbers_dates_times"
    | "inclusive_language"
    | "tone"
    | "specific_conventions"
    | "clarity_and_readability"
    | "other";
export const StyleGuideCategory = {
    Punctuation: "punctuation",
    Capitalization: "capitalization",
    SpellingAndGrammar: "spelling_and_grammar",
    NumbersDatesTimes: "numbers_dates_times",
    InclusiveLanguage: "inclusive_language",
    Tone: "tone",
    SpecificConventions: "specific_conventions",
    ClarityAndReadability: "clarity_and_readability",
    Other: "other",
} as const;
