/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StyleGuides = "ap" | "chicago" | "microsoft" | "style_brand_importer";
export const StyleGuides = {
    Ap: "ap",
    Chicago: "chicago",
    Microsoft: "microsoft",
    StyleBrandImporter: "style_brand_importer",
} as const;
