/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

/**
 * The sub-category of the change
 */
export type Subcategory =
    | MarkupAI.GrammarCategory
    | MarkupAI.SimpleVocabCategory
    | MarkupAI.SentenceStructureCategory
    | MarkupAI.SentenceLengthCategory
    | MarkupAI.ToneCategory
    | MarkupAI.StyleGuideCategory
    | MarkupAI.TermReplaceCategory;
