/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface SuggestionOriginalContent {
    issues?: MarkupAI.Suggestion[];
    scores?: MarkupAI.ScoreOutput;
}
