/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface SuggestionResponse {
    config?: MarkupAI.ConfigOptions;
    original?: MarkupAI.SuggestionOriginalContent;
    workflow: MarkupAI.WorkflowInfo;
}
