/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface TermSetResult {
    instructions: string;
    terms: MarkupAI.TermItem[];
    matched_terms: MarkupAI.MatchedTerm[];
}
