/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface TerminologySearchResponse {
    results: MarkupAI.TermSetResult[];
}
