/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

/**
 * Payload to create a new term for a term set
 */
export interface TermCreateRequest {
    term: string;
    type: MarkupAI.TermType;
}
