/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TermReplaceCategory = "Terminology" | "other";
export const TermReplaceCategory = {
    Terminology: "Terminology",
    Other: "other",
} as const;
