/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TermReplaceCategory = "term" | "other";
export const TermReplaceCategory = {
    Term: "term",
    Other: "other",
} as const;
