/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

/**
 * Detailed term information for term management UI
 */
export interface TermDetail {
    id: string;
    term: string;
    type: MarkupAI.TermType;
    created_at: string;
    updated_at: string;
    created_by?: string;
    updated_by?: string;
}
