/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * DB-mapped representation of a term set (no terms).
 */
export interface TermSetResponse {
    id: string;
    instructions: string;
    created_at: string;
    updated_at: string;
    created_by?: string;
    updated_by?: string;
}
