/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

/**
 * Term set with all associated terms for term management UI
 */
export interface TermSetWithTerms {
    id: string;
    instructions: string;
    created_at: string;
    updated_at: string;
    created_by?: string;
    updated_by?: string;
    terms: MarkupAI.TermDetail[];
    domains?: MarkupAI.DomainSummary[];
}
