/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents the three types of terms in the terminology system.
 */
export type TermType = "preferred" | "prohibited" | "context_dependent";
export const TermType = {
    Preferred: "preferred",
    Prohibited: "prohibited",
    ContextDependent: "context_dependent",
} as const;
