/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToneCategory = "word_choice" | "syntax" | "punctuation" | "discourse_features" | "implicit_style" | "other";
export const ToneCategory = {
    WordChoice: "word_choice",
    Syntax: "syntax",
    Punctuation: "punctuation",
    DiscourseFeatures: "discourse_features",
    ImplicitStyle: "implicit_style",
    Other: "other",
} as const;
