/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Tones =
    | "academic"
    | "confident"
    | "conversational"
    | "empathetic"
    | "engaging"
    | "friendly"
    | "professional"
    | "technical";
export const Tones = {
    Academic: "academic",
    Confident: "confident",
    Conversational: "conversational",
    Empathetic: "empathetic",
    Engaging: "engaging",
    Friendly: "friendly",
    Professional: "professional",
    Technical: "technical",
} as const;
