/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToneScore {
    score?: number;
    informality?: number;
    liveliness?: number;
    informality_alignment?: number;
    liveliness_alignment?: number;
}
