/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToneScore {
    score?: number;
    informality?: number;
    liveliness?: number;
    target_informality?: number;
    target_liveliness?: number;
    informality_tolerance?: number;
    liveliness_tolerance?: number;
}
