/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToneCategory =
    | "Tone-Aligned Wording"
    | "Tone-Shaping Structure"
    | "Tone-Signal Punctuation"
    | "Transitions and Flow"
    | "Additional Tone Changes"
    | "other";
export const ToneCategory = {
    ToneAlignedWording: "Tone-Aligned Wording",
    ToneShapingStructure: "Tone-Shaping Structure",
    ToneSignalPunctuation: "Tone-Signal Punctuation",
    TransitionsAndFlow: "Transitions and Flow",
    AdditionalToneChanges: "Additional Tone Changes",
    Other: "other",
} as const;
