/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Tones = "academic" | "business" | "conversational" | "formal" | "informal" | "technical";
export const Tones = {
    Academic: "academic",
    Business: "business",
    Conversational: "conversational",
    Formal: "formal",
    Informal: "informal",
    Technical: "technical",
} as const;
