/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WorkflowStatus = "running" | "completed" | "failed" | "not_found";
export const WorkflowStatus = {
    Running: "running",
    Completed: "completed",
    Failed: "failed",
    NotFound: "not_found",
} as const;
