/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index.js";

export interface WorkflowInfo {
    /** Workflow ID */
    id: string;
    /** API version */
    api_version?: string;
    /** The original name of the file passed into the workflow */
    filename?: string;
    /** UTC timestamp when the result was generated */
    generated_at?: string;
    status?: MarkupAI.WorkflowStatus;
    /** Workflow type: checks, suggestions, or rewrites */
    type: string;
    /** The status code received and URL used when sending the webhook if a webhook URL was included when starting the process. */
    webhook_response?: MarkupAI.WebhookResponse;
}
