/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MarkupAI from "../index";

export interface WorkflowResponse {
    status: MarkupAI.WorkflowStatus;
    workflow_id: string;
}
