/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { MarkupAIClient } from "../../src/Client";
import * as MarkupAI from "../../src/api/index";

describe("StyleGuides", () => {
    test("listStyleGuides (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "123e4567-e89b-12d3-a456-426614174000",
                name: "Custom Marketing Guide",
                created_at: "2025-01-20T14:30:00Z",
                created_by: "user123",
                status: "completed",
                updated_at: "2024-01-15T09:30:00Z",
                updated_by: "updated_by",
                summary: "This is the summary generated for this style guide",
                base_style_guide_type: "ap",
                terminology_domain_ids: ["223e4567-e89b-12d3-a456-426614174000"],
            },
            {
                id: "01971e03-dd27-75ee-9044-b48e654848cf",
                name: "AP",
                created_at: "2025-07-15T00:00:00Z",
                created_by: "markupai",
                status: "completed",
                updated_at: "2024-01-15T09:30:00Z",
                updated_by: "updated_by",
                summary: "This is the summary generated for this style guide",
                base_style_guide_type: "ap",
                terminology_domain_ids: ["terminology_domain_ids"],
            },
        ];
        server.mockEndpoint().get("/v1/style-guides").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.styleGuides.listStyleGuides();
        expect(response).toEqual([
            {
                id: "123e4567-e89b-12d3-a456-426614174000",
                name: "Custom Marketing Guide",
                created_at: "2025-01-20T14:30:00Z",
                created_by: "user123",
                status: "completed",
                updated_at: "2024-01-15T09:30:00Z",
                updated_by: "updated_by",
                summary: "This is the summary generated for this style guide",
                base_style_guide_type: "ap",
                terminology_domain_ids: ["223e4567-e89b-12d3-a456-426614174000"],
            },
            {
                id: "01971e03-dd27-75ee-9044-b48e654848cf",
                name: "AP",
                created_at: "2025-07-15T00:00:00Z",
                created_by: "markupai",
                status: "completed",
                updated_at: "2024-01-15T09:30:00Z",
                updated_by: "updated_by",
                summary: "This is the summary generated for this style guide",
                base_style_guide_type: "ap",
                terminology_domain_ids: ["terminology_domain_ids"],
            },
        ]);
    });

    test("listStyleGuides (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/style-guides").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.styleGuides.listStyleGuides();
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("listStyleGuides (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/style-guides").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.styleGuides.listStyleGuides();
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("listStyleGuides (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/style-guides").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.styleGuides.listStyleGuides();
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("listStyleGuides (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/style-guides").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.styleGuides.listStyleGuides();
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("getStyleGuide (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "123e4567-e89b-12d3-a456-426614174000",
            name: "Technical Documentation Guide",
            created_at: "2025-01-10T09:15:00Z",
            created_by: "user456",
            status: "completed",
            updated_at: "2024-01-15T09:30:00Z",
            updated_by: "updated_by",
            summary: "This is the summary generated for this style guide",
            base_style_guide_type: "ap",
            terminology_domain_ids: ["223e4567-e89b-12d3-a456-426614174000", "323e4567-e89b-12d3-a456-426614174000"],
        };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.styleGuides.getStyleGuide("style_guide_id");
        expect(response).toEqual({
            id: "123e4567-e89b-12d3-a456-426614174000",
            name: "Technical Documentation Guide",
            created_at: "2025-01-10T09:15:00Z",
            created_by: "user456",
            status: "completed",
            updated_at: "2024-01-15T09:30:00Z",
            updated_by: "updated_by",
            summary: "This is the summary generated for this style guide",
            base_style_guide_type: "ap",
            terminology_domain_ids: ["223e4567-e89b-12d3-a456-426614174000", "323e4567-e89b-12d3-a456-426614174000"],
        });
    });

    test("getStyleGuide (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.getStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("getStyleGuide (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.getStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("getStyleGuide (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.getStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.NotFoundError);
    });

    test("getStyleGuide (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.getStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("getStyleGuide (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.getStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("deleteStyleGuide (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/style-guides/style_guide_id").respondWith().statusCode(200).build();

        const response = await client.styleGuides.deleteStyleGuide("style_guide_id");
        expect(response).toEqual(undefined);
    });

    test("deleteStyleGuide (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.deleteStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("deleteStyleGuide (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.deleteStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("deleteStyleGuide (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.deleteStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.NotFoundError);
    });

    test("deleteStyleGuide (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.deleteStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("deleteStyleGuide (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/style-guides/style_guide_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.deleteStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("updateStyleGuide (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "My Custom Style Guide",
            created_at: "2025-07-15T16:20:14Z",
            created_by: "37bb339a-d71e-4613-b3ea-8ddab41e9e7d",
            status: "running",
            updated_at: "2024-01-15T09:30:00Z",
            updated_by: "updated_by",
            summary: "summary",
            base_style_guide_type: "ap",
            terminology_domain_ids: ["terminology_domain_ids"],
        };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.styleGuides.updateStyleGuide("style_guide_id");
        expect(response).toEqual({
            id: "id",
            name: "My Custom Style Guide",
            created_at: "2025-07-15T16:20:14Z",
            created_by: "37bb339a-d71e-4613-b3ea-8ddab41e9e7d",
            status: "running",
            updated_at: "2024-01-15T09:30:00Z",
            updated_by: "updated_by",
            summary: "summary",
            base_style_guide_type: "ap",
            terminology_domain_ids: ["terminology_domain_ids"],
        });
    });

    test("updateStyleGuide (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("updateStyleGuide (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("updateStyleGuide (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.NotFoundError);
    });

    test("updateStyleGuide (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.ConflictError);
    });

    test("updateStyleGuide (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("updateStyleGuide (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/style-guides/style_guide_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.styleGuides.updateStyleGuide("style_guide_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });
});
