/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { MarkupAIClient } from "../../src/Client";
import * as MarkupAI from "../../src/api/index";

describe("Terminology", () => {
    test("exportTerminology (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/terminology").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.terminology.exportTerminology();
        expect(response).toEqual({
            key: "value",
        });
    });

    test("exportTerminology (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/terminology").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.terminology.exportTerminology();
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("exportTerminology (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/terminology").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.terminology.exportTerminology();
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("exportTerminology (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server.mockEndpoint().get("/v1/terminology").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.terminology.exportTerminology();
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("searchTerminology (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            results: [
                {
                    instructions: "instructions",
                    terms: [{ term: "term", type: "type" }],
                    matched_terms: [{ term: "term", matched_ngram: "matched_ngram" }],
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.searchTerminology({
            query: "query",
        });
        expect(response).toEqual({
            results: [
                {
                    instructions: "instructions",
                    terms: [
                        {
                            term: "term",
                            type: "type",
                        },
                    ],
                    matched_terms: [
                        {
                            term: "term",
                            matched_ngram: "matched_ngram",
                        },
                    ],
                },
            ],
        });
    });

    test("searchTerminology (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/search")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.searchTerminology({
                query: "query",
            });
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("searchTerminology (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/search")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.searchTerminology({
                query: "query",
            });
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("searchTerminology (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/search")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.searchTerminology({
                query: "query",
            });
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("searchTerminology (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/search")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.searchTerminology({
                query: "query",
            });
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("listTermSets (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            term_sets: [
                {
                    id: "id",
                    instructions: "instructions",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                    terms: [
                        {
                            id: "id",
                            term: "term",
                            type: "preferred",
                            created_at: "2024-01-15T09:30:00Z",
                            updated_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    domains: [{ id: "id", name: "name" }],
                },
            ],
            total_count: 1,
            total_unfiltered_term_sets: 1,
            page: 1,
            page_size: 1,
            total_pages: 1,
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.listTermSets({
            page: 1,
            page_size: 1,
            search_term: "search_term",
        });
        expect(response).toEqual({
            term_sets: [
                {
                    id: "id",
                    instructions: "instructions",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                    terms: [
                        {
                            id: "id",
                            term: "term",
                            type: "preferred",
                            created_at: "2024-01-15T09:30:00Z",
                            updated_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    domains: [
                        {
                            id: "id",
                            name: "name",
                        },
                    ],
                },
            ],
            total_count: 1,
            total_unfiltered_term_sets: 1,
            page: 1,
            page_size: 1,
            total_pages: 1,
        });
    });

    test("listTermSets (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listTermSets();
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("listTermSets (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listTermSets();
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("listTermSets (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listTermSets();
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("listTermSets (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listTermSets();
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("createTermSet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = {
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.createTermSet({
            instructions: "instructions",
        });
        expect(response).toEqual({
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        });
    });

    test("createTermSet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTermSet({
                instructions: "instructions",
            });
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("createTermSet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTermSet({
                instructions: "instructions",
            });
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("createTermSet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTermSet({
                instructions: "instructions",
            });
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("createTermSet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTermSet({
                instructions: "instructions",
            });
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("getTermSet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            terms: [
                {
                    id: "id",
                    term: "term",
                    type: "preferred",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                },
            ],
            domains: [{ id: "id", name: "name" }],
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.getTermSet("term_set_id");
        expect(response).toEqual({
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            terms: [
                {
                    id: "id",
                    term: "term",
                    type: "preferred",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                },
            ],
            domains: [
                {
                    id: "id",
                    name: "name",
                },
            ],
        });
    });

    test("getTermSet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("getTermSet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("getTermSet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("getTermSet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("deleteTermSet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/terminology/term-sets/term_set_id").respondWith().statusCode(200).build();

        const response = await client.terminology.deleteTermSet("term_set_id");
        expect(response).toEqual(undefined);
    });

    test("deleteTermSet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("deleteTermSet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("deleteTermSet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("deleteTermSet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("updateTermSet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        };
        server
            .mockEndpoint()
            .patch("/v1/terminology/term-sets/term_set_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.updateTermSet("term_set_id");
        expect(response).toEqual({
            id: "id",
            instructions: "instructions",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        });
    });

    test("updateTermSet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/term-sets/term_set_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("updateTermSet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/term-sets/term_set_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("updateTermSet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/term-sets/term_set_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("updateTermSet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/term-sets/term_set_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTermSet("term_set_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("createTerm (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = {
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets/term_set_id/terms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.createTerm("term_set_id", {
            term: "term",
            type: "preferred",
        });
        expect(response).toEqual({
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        });
    });

    test("createTerm (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets/term_set_id/terms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTerm("term_set_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("createTerm (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets/term_set_id/terms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTerm("term_set_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("createTerm (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets/term_set_id/terms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTerm("term_set_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("createTerm (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/term-sets/term_set_id/terms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createTerm("term_set_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("getTerm (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.getTerm("term_set_id", "term_id");
        expect(response).toEqual({
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        });
    });

    test("getTerm (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("getTerm (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("getTerm (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("getTerm (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("updateTerm (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = {
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        };
        server
            .mockEndpoint()
            .put("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.updateTerm("term_set_id", "term_id", {
            term: "term",
            type: "preferred",
        });
        expect(response).toEqual({
            id: "id",
            term: "term",
            type: "preferred",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
        });
    });

    test("updateTerm (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .put("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTerm("term_set_id", "term_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("updateTerm (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .put("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTerm("term_set_id", "term_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("updateTerm (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTerm("term_set_id", "term_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("updateTerm (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { term: "term", type: "preferred" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .put("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateTerm("term_set_id", "term_id", {
                term: "term",
                type: "preferred",
            });
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("deleteTerm (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.terminology.deleteTerm("term_set_id", "term_id");
        expect(response).toEqual(undefined);
    });

    test("deleteTerm (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("deleteTerm (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("deleteTerm (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("deleteTerm (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/term-sets/term_set_id/terms/term_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteTerm("term_set_id", "term_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("listDomains (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            domains: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                    term_set_count: 1,
                },
            ],
            total_count: 1,
            page: 1,
            page_size: 1,
            total_pages: 1,
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.listDomains({
            page: 1,
            page_size: 1,
            search: "search",
        });
        expect(response).toEqual({
            domains: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    created_by: "created_by",
                    updated_by: "updated_by",
                    term_set_count: 1,
                },
            ],
            total_count: 1,
            page: 1,
            page_size: 1,
            total_pages: 1,
        });
    });

    test("listDomains (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listDomains();
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("listDomains (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listDomains();
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("listDomains (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listDomains();
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("listDomains (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.listDomains();
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("createDomain (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        };
        server
            .mockEndpoint()
            .post("/v1/terminology/domains")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.createDomain({
            name: "name",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        });
    });

    test("createDomain (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/domains")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createDomain({
                name: "x",
            });
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("createDomain (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/domains")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createDomain({
                name: "x",
            });
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("createDomain (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/terminology/domains")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createDomain({
                name: "x",
            });
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("createDomain (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .post("/v1/terminology/domains")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.createDomain({
                name: "x",
            });
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("getDomain (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.getDomain("domain_id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        });
    });

    test("getDomain (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("getDomain (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getDomain("domain_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("getDomain (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("getDomain (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .get("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.getDomain("domain_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("deleteDomain (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/terminology/domains/domain_id").respondWith().statusCode(200).build();

        const response = await client.terminology.deleteDomain("domain_id");
        expect(response).toEqual(undefined);
    });

    test("deleteDomain (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("deleteDomain (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteDomain("domain_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("deleteDomain (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("deleteDomain (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .delete("/v1/terminology/domains/domain_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.deleteDomain("domain_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });

    test("updateDomain (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        };
        server
            .mockEndpoint()
            .patch("/v1/terminology/domains/domain_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.terminology.updateDomain("domain_id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_by: "created_by",
            updated_by: "updated_by",
            term_set_count: 1,
        });
    });

    test("updateDomain (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/domains/domain_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnauthorizedError);
    });

    test("updateDomain (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/domains/domain_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateDomain("domain_id");
        }).rejects.toThrow(MarkupAI.ForbiddenError);
    });

    test("updateDomain (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/domains/domain_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateDomain("domain_id");
        }).rejects.toThrow(MarkupAI.UnprocessableEntityError);
    });

    test("updateDomain (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MarkupAIClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { detail: "detail", status: 1, request_id: "request_id" };
        server
            .mockEndpoint()
            .patch("/v1/terminology/domains/domain_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.terminology.updateDomain("domain_id");
        }).rejects.toThrow(MarkupAI.InternalServerError);
    });
});
