/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { StyleGuides } from "./api/resources/styleGuides/client/Client.js";
import { StyleChecks } from "./api/resources/styleChecks/client/Client.js";
import { StyleSuggestions } from "./api/resources/styleSuggestions/client/Client.js";
import { StyleRewrites } from "./api/resources/styleRewrites/client/Client.js";
import { Terminology } from "./api/resources/terminology/client/Client.js";

export declare namespace MarkupAIClient {
    export interface Options {
        environment?: core.Supplier<environments.MarkupAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class MarkupAIClient {
    protected readonly _options: MarkupAIClient.Options;
    protected _styleGuides: StyleGuides | undefined;
    protected _styleChecks: StyleChecks | undefined;
    protected _styleSuggestions: StyleSuggestions | undefined;
    protected _styleRewrites: StyleRewrites | undefined;
    protected _terminology: Terminology | undefined;

    constructor(_options: MarkupAIClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@markupai/api",
                    "X-Fern-SDK-Version": "1.5.0",
                    "User-Agent": "@markupai/api/1.5.0",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get styleGuides(): StyleGuides {
        return (this._styleGuides ??= new StyleGuides(this._options));
    }

    public get styleChecks(): StyleChecks {
        return (this._styleChecks ??= new StyleChecks(this._options));
    }

    public get styleSuggestions(): StyleSuggestions {
        return (this._styleSuggestions ??= new StyleSuggestions(this._options));
    }

    public get styleRewrites(): StyleRewrites {
        return (this._styleRewrites ??= new StyleRewrites(this._options));
    }

    public get terminology(): Terminology {
        return (this._terminology ??= new Terminology(this._options));
    }
}
