/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MarkupAIEnvironment = {
    Default: "https://api.markup.ai",
} as const;

export type MarkupAIEnvironment = typeof MarkupAIEnvironment.Default;
