/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MarkupAIEnvironment = {
    Production: "https://app.acrolinx.cloud",
} as const;

export type MarkupAIEnvironment = typeof MarkupAIEnvironment.Production;
